spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.128:3306/study-spring-boot-mybatis-plus
    username: root
    password: 123456

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
#    root: warn
    com:
      fengwenyi:
        studyspringbootmybatisplus:
          db:
            mapper: trace
#  pattern:
#    console: '%p%m%n'