
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
  mvc:
    # 静态资源访问路径
    static-path-pattern: /static/**

jwt:
  secret: secret
  expiration: 300000
  header: token
#  header: Authorization
